// This file is "main.dart"
//
//*****flutter pub run build_runner build*****
//
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'record.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'record.g.dart';

@freezed
class Record with _$Record {
  factory Record(
      {required int weight,
      required DateTime dateTime,
      String? note,
      String? photoUrl}) = _Record;
  factory Record.fromJson(Map<String, dynamic> json) => _$RecordFromJson(json);
}

// @freezed
// class Person with _$Person {
//   const factory Person({
//     required String firstName,
//     required String lastName,
//     required int age,
//   }) = _Person;
//
//   factory Person.fromJson(Map<String, Object?> json)
//   => _$PersonFromJson(json);
// }
